const SET_SIGN_UP_ERROR = 'SET_SIGN_UP_ERROR';
const SET_SIGN_UP_ERROR_MESSAGE = 'SET_SIGN_UP_ERROR_MESSAGE';
const SET_SIGN_UP_ERROR_STATUS = 'SET_SIGN_UP_ERROR_STATUS';
const SET_SIGN_UP_ERROR_DISPLAY = 'SET_SIGN_UP_ERROR_DISPLAY';
const SET_AUTHENTICATION_STATUS = 'SET_AUTHENTICATION_STATUS';
const SET_USER_DATA_LOADING = 'SET_USER_DATA_LOADING';
const SET_USER_DATA_SUCCESS = 'SET_USER_DATA_SUCCESS';
const SET_USER_DATA_ERROR = 'SET_USER_DATA_ERROR';
const SET_USER_QUESTION_DATA_LOADING = 'SET_USER_QUESTION_DATA_LOADING';
const SET_USER_QUESTION_DATA_SUCCESS = 'SET_USER_QUESTION_DATA_SUCCESS';
const SET_USER_QUESTION_DATA_ERROR = 'SET_USER_QUESTION_DATA_ERROR';
const SET_QUESTION_DATA_LOADING = 'SET_USER_DATA_LOADING';
const SET_QUESTION_DATA_SUCCESS = 'SET_USER_DATA_SUCCESS';
const SET_QUESTION_DATA_ERROR = 'SET_USER_DATA_ERROR';

export {
    SET_SIGN_UP_ERROR,
    SET_SIGN_UP_ERROR_MESSAGE,
    SET_SIGN_UP_ERROR_DISPLAY,
    SET_SIGN_UP_ERROR_STATUS,
    SET_AUTHENTICATION_STATUS,
    SET_USER_DATA_LOADING,
    SET_USER_DATA_SUCCESS,
    SET_USER_DATA_ERROR,
    SET_USER_QUESTION_DATA_LOADING,
    SET_USER_QUESTION_DATA_SUCCESS,
    SET_USER_QUESTION_DATA_ERROR,
    SET_QUESTION_DATA_LOADING,
    SET_QUESTION_DATA_SUCCESS,
    SET_QUESTION_DATA_ERROR,
};
