const SET_SIGN_UP_ERROR: string = 'SET_SIGN_UP_ERROR';
const SET_SIGN_UP_ERROR_MESSAGE: string = 'SET_SIGN_UP_ERROR_MESSAGE';
const SET_SIGN_UP_ERROR_DISPLAY: string = 'SET_SIGN_UP_ERROR_DISPLAY';
const SET_AUTHENTICATION_STATUS: string = 'SET_AUTHENTICATION_STATUS';
const SET_USER_DATA_LOADING: string = 'SET_USER_DATA_LOADING';
const SET_USER_DATA_SUCCESS: string = 'SET_USER_DATA_SUCCESS';
const SET_USER_DATA_ERROR: string = 'SET_USER_DATA_ERROR';

export {
    SET_SIGN_UP_ERROR,
    SET_SIGN_UP_ERROR_MESSAGE,
    SET_SIGN_UP_ERROR_DISPLAY,
    SET_AUTHENTICATION_STATUS,
    SET_USER_DATA_LOADING,
    SET_USER_DATA_SUCCESS,
    SET_USER_DATA_ERROR,
}
